### ISSUE TITLE
types.go should not contain utility/helper functions

### ISSUE THREAD

**Issue by bparees** [openshift/cluster-samples-operator#117]
We shouldn't have things like this:
https://github.com/openshift/cluster-samples-operator/blob/master/pkg/apis/samples/v1/types.go#L367

types.go should only define structs for external apis, not functions.

I think it's even undesirable to have functions attached to the api structs at all (instead helper functions should be created that take the api object as an argument), but if you can find another example of someone attaching functions to api structs i'll stand corrected.

So my suggestion would be to create a helper/utility package (not part of the apis pkg) and move those functions there as first class helper functions.

Not urgent, but worthwhile cleanup.

**Comment by gabemontero** [comment]
getting addressed with https://github.com/openshift/cluster-samples-operator/pull/197
