### ISSUE TITLE
[api-freeze] Verify operator API is frozen

### ISSUE THREAD

**Issue by adambkaplan** [openshift/cluster-samples-operator#134]
*Backwards compatibility of GA APIs*

What constitutes a backwards compatible API?

1. Fields can not be removed (this also means you can’t rename a field)
2. Serialized defaults can not change.  Unserialized defaults in operators can change over time.
3. Behavior (meaning) of a field can not change.  This means that old fields must be maintained even if new fields supercede them.
4. New fields can be introduced that supercede existing fields, but values in the existing fields must be respected when present.

Other things that should be considered “API”

1. Names of singleton CRs in openshift-config (user-provided) and openshift-config-managed (operator-provided) namespaces that are used for cross-communication of components
2. Names / namespaces of Services used for cross-communication of components
3. Annotations and labels used for cross-communication of components

/assign @gabemontero

**Comment by gabemontero** [comment]
@adambkaplan there no pending changes of the ilk you've detailed in the description
