### ISSUE TITLE
Samples container ignores Proxy setting from proxy.config.openshift.io

### ISSUE THREAD

**Issue by Zouuup** [openshift/cluster-samples-operator#168]
Hello,

Installing behind a corporate proxy, cluster samples Is ignoring the global proxy configuration in proxy.config.openshift.io.

**Comment by gabemontero** [comment]
This has been asked/raised before ... it is not samples operator's job to honor the global proxy config.

Other controllers related to image registry, control plan, openshift-apiserver manage this on its behalf.

@bparees @adambkaplan FYI / please augment / corrrect if needed.

**Comment by bparees** [comment]
confirmed.  Presumably the issue you are hitting is either that the imagestreamcontroller isn't (yet) picking up the proxy config so it can't import the imagestream the samples operator created, or the registry isn't, so it can't pullthrough the content for you.

Also not sure why this is opened as a github issue, there's no proxy support in OCP4.1 today for this, and it's being added in 4.2.  If we think there are implementation problems in 4.2 they should be opened as BZ to ensure they block the 4.2 release appropriately.
