### ISSUE TITLE
RFE - Add feature to switch ImageStream source registries.

### ISSUE THREAD

**Issue by nnachefski** [openshift/cluster-samples-operator#185]
I'm working with Openshift 4.2 pre-release.  I performed a disconnected installation where i mirror images locally and then install from there.  I use the 'oc adm release mirror' feature to mirror the platform's images.  I also have a python script that mirrors the various non-platform (application specific) images.  Additionally, i have a python script that is run post-install that patches all the ImageStream specs to point to the local registry.  It would seem that it would be more elegant if this patching of imagestreams could be done by this particular operator (openshift-samples).

My request is to provide a feature where i can easily change the source registry for all image streams that are deployed during the install process.   Similar to OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE for the platform images.

-Nick

**Comment by gabemontero** [comment]
Thanks for the feedback @nnachefski 

You can already override the registry with the SamplesRegistry config setting for the samples operator

https://github.com/openshift/cluster-samples-operator#configuration

https://github.com/openshift/cluster-samples-operator/blob/master/pkg/apis/samples/v1/types.go#L89-L93

Note, there is also an item in the devexp epic list to do even more complex replacements of both the registry and repository of given image references

See https://docs.google.com/document/d/15gr5VzAB2C_VTBzghgv26GbnZqVi5YeknTu0zID1li4/edit

@siamaksade @adambkaplan FYI
