### ISSUE TITLE
s390x - OpenShift installer does not detect cluster-samples-operator readiness

### ISSUE THREAD

**Issue by dbenoit17** [openshift/cluster-samples-operator#203]
On the latest commit on s390x, the cluster samples operator is reporting that it is available and finished progressing, however the openshift installer is not detecting that the operator has finished updating, and ends up timing out.

```DEBUG OpenShift Installer v4.2.10                  
DEBUG Built from commit 6ed04f65b0f6a1e11f10afe658465ba8195ac459 
INFO Waiting up to 30m0s for the cluster at https://api.test.example.com:6443 to initialize... 
DEBUG Still waiting for the cluster to initialize: Cluster operator openshift-samples is still updating```

**Comment by yselkowitz** [comment]
@gabemontero @bparees we believe this is a regression in https://github.com/openshift/cluster-samples-operator/pull/187

**Comment by bparees** [comment]
@yselkowitz @dbenoit17 can you open this as a bugzilla?

**Comment by yselkowitz** [comment]
Please note that we are looking for an (urgent) fix for #187 not necessarily a revert, as we do need the overall functionality

**Comment by bparees** [comment]
@yselkowitz can you show us what the samplers operator clusteroperator resource is reporting so we can understand why the installer might not be recognizing it is finished?

**Comment by yselkowitz** [comment]
Filed https://bugzilla.redhat.com/show_bug.cgi?id=1779933; @dbenoit17 will have to provide any additional information on the issue.

**Comment by gabemontero** [comment]
/close

in favor of bugzilla
