### ISSUE TITLE
samples operator should wait for registry to exist

### ISSUE THREAD

**Issue by bparees** [openshift/cluster-samples-operator#25]
for complex reasons i can explain in person, it would be best if the samples operator did not install the samples until after we know the registry has been installed.

Unfortunately this means checking at least two places for the registry:

1) the default namespace (3.11 and earlier)
2) the openshift-image-registry namespace (4.0 and beyond, assuming migration has happened or a clean install)

There may be other things we can block the installation on, fundamentally we need to ensure that the openshift apiserver knows what the `internalRegistryHostname` is before we install the imagestreams, and the registry operator will be responsible for providing that value to the apiserver.  (We may be able to just check for the value directly, in the same way the apiserver picks up the value..that might be better than looking for a registry to be running).

**Comment by gabemontero** [comment]
Can we look up the registry operator's custom resource and check for a condition indicating whether the registry is up?  Presumably the registry operator is already dealing with the registry running in either namespace, right?

**Comment by bparees** [comment]
> Can we look up the registry operator's custom resource and check for a condition indicating whether the registry is up?

no because in the case of a 3.11 migration the registry operator may not be able to take over/come up, but the internalHostName configuration will still be present.

**Comment by gabemontero** [comment]
Took a bit of a stroll down the `internalRegistryHostname` path ... saw how the value in the config file is processed and propagated, but did see a viable way that my operator pod could interact with the api server to get the value.

To closest, albeit still seemingly non-viable, option was the deprecated env var that is set (but can be overrided by the config value specified for `internalRegistryHostname`.  Assuming that env is set in every pod when the registry is available (I did not explore to confirm or deny that), that could have been a way.

But due diligence warrants a discussion with the SMEs in this space.

Certainly checking for the presence of pods/services of a given prefix/name is more in line with what the samples operator currently does.

**Comment by bparees** [comment]
The config mechanism for that value will also be changing in 4.0, the values will come out of a configmap, so it will be easier for your operator to track down and examine at that point.

**Comment by gabemontero** [comment]
ah yeah I have caught wind of some of that ..... ok, so hold tight on doing this until that arrives, and no intermediate solution of looking for the service/pod, right?

**Comment by bparees** [comment]
> ok, so hold tight on doing this until that arrives, and no intermediate solution of looking for the service/pod, right?

yeah, let's hold on this until some other pieces fall into place/mature.

**Comment by gabemontero** [comment]
OK, brought up and installer based cluster, and I found the config map with the old master-config.yaml data, including `internalRegistryHostname`

And in looking at registry pods, given the current state of this writing, and see both the default and new registry operator namespaces with running registry pods.

However, talked with @deads2k, showed him what I found, and he says that master-config.yaml data being stored in the 4.0 config map is going away.

So a new gating mechanism appears needed @bparees

**Comment by gabemontero** [comment]
Confirmed this is no longer needed.  Quote from @bparees:  `I put changes into the controller manager operator that should ensure it doesn't matter anymore.`
