### ISSUE TITLE
Using Jenkins in an offline-installation scenario

### ISSUE THREAD

**Issue by mriedmann** [openshift/cluster-samples-operator#302]
We are currently tying to get the Samples-Operator Jenkins-Template working in a air-gapped/offline Installation scenario. We set the `samplesRegistry` value to our on-site mirror-registry and all Imagestreams, except the Jenkins and Jenkins-Agent ones are mapped correctly. 

Can someone please give a hint how to fix this? 
I tried to set the jenkins-image env-vars on the operator deployment manually without any luck (resets after some minutes).

Thank you!

**Comment by gabemontero** [comment]
Yeah there was a bugzilla on this in April of this year

For 4.4, you need a 4.4 level with the fix from https://bugzilla.redhat.com/show_bug.cgi?id=1824280
For 4.3, you need a 4.3 level with the fix from  https://bugzilla.redhat.com/show_bug.cgi?id=1826028
