### ISSUE TITLE
Samples Bump for OCP 4.4?

### ISSUE THREAD

**Issue by MichaelWasher** [openshift/cluster-samples-operator#323]
Hi team,

What's the deals with samples bumps with relation to release-versions for OpenShift?

I can see that there has been a samples-bump for OpenShift 4.5 resulting in OpenJDK18:1.8 tag being present and managed by the Samples Operator in OpenShift 4.5[0] but is not present in OCP 4.4[1].

Is it expected that I need to upgrade to OpenShift 4.5 to get the samples-bump, or is there some other process that results in bringing the Samples Operator desired image-streams more inline with the library repo?[2]
~~~ References
[0] https://github.com/openshift/cluster-samples-operator/blob/release-4.4/tmp/build/assets/operator/ocp-x86_64/java/imagestreams/redhat-openjdk18-openshift-rhel7.json
[1] https://github.com/openshift/cluster-samples-operator/blob/release-4.5/tmp/build/assets/operator/ocp-x86_64/java/imagestreams/redhat-openjdk18-openshift-rhel7.json
[2] https://github.com/openshift/library/

**Comment by gabemontero** [comment]
The policy is that as sample providers like the open jdk team provide new tags and image versions in their imagestreams, they are only picked up in the current OCP release at the time of their addition, and then any future releases.

We do not backport new tags to releases already out in the field.

Aside from the upgrade option, a customer admistrator certainly is free to add or update imagestreams on their own, using the source in openshift/library.

For example 

`oc apply -n openshift -f https://raw.githubusercontent.com/openshift/library/master/official/java/imagestreams/redhat-openjdk18-openshift-rhel-x86_64.json`

would add the tag they are interested in to their 4.4 cluster.

**Comment by MichaelWasher** [comment]
Thanks for the explanation @gabemontero !
