### ISSUE TITLE
Several High Vulnerabilities in Referenced Images

### ISSUE THREAD

**Issue by afflom** [openshift/cluster-samples-operator#383]
https://github.com/openshift/cluster-samples-operator/blob/release-4.8/manifests/image-references 

This file references an image with 17 High vulnerabilities. 

![image](https://user-images.githubusercontent.com/30676559/127346814-a6d40338-e529-438b-bc97-0a694bef63de.png)

**Comment by gabemontero** [comment]
Hey @afflom 

This is the same core question/issue as https://github.com/openshift/cluster-samples-operator/issues/356

I am going to close this in favor of that one, and continue the discussion there.  Please subscribe to that one as you see fit.

The quick explanation:  not removing imagestreamtags to images that upstream has removed references to is currently an explicit choice by this operator, so as to not disrupt current deployments/builds.  Manual remove by cluster admins is expected.  Also, the images themselves are owned by SCL and RH middleware.

That said, with the uptick around wanting a more automated solution, we may entertain new features to the operator to augment the behavior here.

/close
