### ISSUE TITLE
Red Hat registry credentials seem to be required for OKD4

### ISSUE THREAD

**Issue by rassie** [openshift/cluster-samples-operator#404]
(opening an issue as requested on Slack https://kubernetes.slack.com/archives/C6AD6JM17/p1637833592421600)

In my OKD4 cluster the `SamplesMissingTBRCredential` alert is always firing, with the message
> The samples operator cannot find credentials for 'registry.redhat.io'. Many of the sample ImageStreams will fail to import unless the 'samplesRegistry' in the operator configuration is changed.

While I understand why this alert would be firing in an OCP cluster, in an OKD cluster a typical user would not have a contract with Red Hat and thus would have no means to obtain the needed credentials (apart from missing licenses for the products inside the registry). Is this somehow expected and if not, could it be fixed? Is this possibly a configuration problem on my side?

Issue valid for at least for `cluster-samples-operator` version `4.9.0-0.okd-2021-11-28-035710` and certainly several versions before that.

**Comment by rassie** [comment]
While we are at it: is anyone looking at the issues at all?

**Comment by gabemontero** [comment]
@dperaza4dustbit we should work with @vrutkovs as to the best way for the operator to determine if it is OCP or OKD.

If there is not a cluster resource we can query, maybe we can update a file in the image payload when we are building the image (that is when we currently know if we are OCP or OKD)

**Comment by mattttv** [comment]
this problem persists in OKD 4.13. - I removed the sample operator to fix this:
oc edit configs.samples.operator.openshift.io
-> set spec.managedState from Managed to Removed

**Comment by h3ct0rjs** [comment]
Hi Guys, 

Hope you're doing great @vrutkovs  this still appears in my last install, I was wondering about this, and lucky me I found this thread. 

I'm currently using : 

4.13.0-0.okd-2023-09-30-084937

Should I remove the operator? or are we able to use the sample operator. 

Regards, 
H

**Comment by vrutkovs** [comment]
You can't remove core operators like sample operator. Please file a new ticket at https://issues.redhat.com for OCP to disable this alert for OKD

**Comment by h3ct0rjs** [comment]
Sure I will let my partner @jhonnier-sys do this activity. In the meantime, best solution would be silencing this alarm. 

Best Regards, 
H
